---

- name: Install ceph drivers for rbd persistent volumes
  apt: name=ceph-common state=installed update_cache=true force=yes
  become: yes
  notify:
    - restart kubelet

- name: Kubecontroller with ceph
  template:
    src: templates/kube-controller-manager.yml.j2
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
  become: yes
  when: kubernetes_node_type == 'admin'
