---

- name: kubernetes repo
  git:
    repo: https://github.com/kubernetes/examples
    dest: ~/kubernetes-examples

- name: elastic pods
  shell: kubectl create -f staging/elasticsearch/
  args:
    chdir: ~/kubernetes-examples
