---

- name: Install pip
  apt: name=python3-pip state=installed update_cache=true force=yes
  become: yes

- name: Install pyaml
  pip: name=pyaml executable=pip3
  become: yes

- name: Install jinja2
  pip: name=jinja2 executable=pip3
  become: yes

- name: Install jinja2-cli
  pip: name=jinja2-cli executable=pip3
  become: yes

- name: Install sigill
  shell: >
    curl -L "https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_0.4.0_$(uname -sm|tr \  _).tgz" | tar -zxC /usr/local/bin;
  become: yes

- name: Grant permissions for ceph (!!! no secure)
  shell: kubectl create -f https://github.com/ReSearchITEng/kubeadm-playbook/raw/master/allow-all-all-rbac.yml

- name: Add all nodes as storage provider
  shell: kubectl label nodes node-type=storage --all

- name: ceph container repo
  git:
    repo: https://github.com/ceph/ceph-container
    dest: ~/ceph-container

- name: create ceph cluster
  shell: >
    ./create_secrets.sh;
    sed -i "s;/dev/sdc;/dev/sdb;g" ceph-osd-prepare-v1-ds.yaml;
    sed -i "s;/dev/sdc;/dev/sdb;g" ceph-osd-activate-v1-ds.yaml;
    kubectl create
    -f ceph-mds-v1-dp.yaml
    -f ceph-mon-v1-svc.yaml
    -f ceph-mon-v1-dp.yaml
    -f ceph-mon-check-v1-dp.yaml
    -f ceph-osd-prepare-v1-ds.yaml
    --namespace=ceph;
  environment:
    PATH: /home/{{ ansible_user }}/.local/bin:{{ ansible_env.PATH }}
    osd_cluster_network: 10.0.0.0/8
    osd_public_network: 10.0.0.0/8
    global_mon_host: ceph-mon.ceph
  args:
    chdir: ~/ceph-container/examples/kubernetes

- name: Ensure ceph disks are ready
  pause:
    minutes: 4

- name: Activate osd nodes
  shell: >
    kubectl delete -f ceph-osd-prepare-v1-ds.yaml --namespace=ceph;
    kubectl create -f ceph-osd-activate-v1-ds.yaml --namespace=ceph;
    sed -i "s;/dev/sdb;/dev/sdc;g" ceph-osd-prepare-v1-ds.yaml;
    sed -i "s;/dev/sdb;/dev/sdc;g" ceph-osd-activate-v1-ds.yaml;
  environment:
    osd_cluster_network: 10.0.0.0/8
    osd_public_network: 10.0.0.0/8
    global_mon_host: ceph-mon.ceph
  args:
    chdir: ~/ceph-container/examples/kubernetes

- name: write ceph.conf for k8s master
  copy:
    remote_src: yes
    src: /home/{{ ansible_user }}/ceph-container/examples/kubernetes/generator/ceph.conf
    dest: /etc/ceph/ceph.conf
    owner: root
  become: yes

- name: write ceph keyring for k8s master
  copy:
    remote_src: yes
    src: /home/{{ ansible_user }}/ceph-container/examples/kubernetes/generator/ceph.client.admin.keyring
    dest: /etc/ceph/keyring
    owner: root
  become: yes

- name: change ceph mon endpoint
  shell: sed -i "s/mon_host = ceph-mon$/mon_host = ceph-mon.ceph/" /etc/ceph/ceph.conf
  become: yes

- name: Ensure ceph osds and mons is running and ready
  pause:
    minutes: 2

- name: create hddpool
  shell: ceph osd pool create hddpool 128

- name: Avoid error "set mismatch, my XXXXXX < server's XXXXXX, missing 40000000"
  shell: ceph osd crush tunables legacy

- name: ceph manifests folder
  file:
    path: ~/ceph
    state: directory
    mode: 0755

- name: Add rbd storage class
  template:
    src: templates/slow_storageclass.yaml.j2
    dest: ~/ceph/slow_storageclass.yaml
    mode: 0755

- name: create slow storage class
  shell: >
    kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/external-storage/master/ceph/rbd/deploy/non-rbac/deployment.yaml --namespace=ceph;
    kubectl create -f slow_storageclass.yaml;
  args:
    chdir: ~/ceph
