---

- name: kubespark repo
  git:
    repo: https://github.com/apache-spark-on-k8s/spark
    dest: ~/kubespark

- name: compile spark
  shell: >
    build/./mvn install -Pkubernetes -pl resource-managers/kubernetes/core -am -DskipTests;
  args:
    chdir: ~/kubespark

- name: make binary
  shell: >
    dev/make-distribution.sh --tgz -Phadoop-2.7 -Pkubernetes
  args:
    chdir: ~/kubespark

- name: launch stagin server
  shell: >
    kubectl create -f conf/kubernetes-resource-staging-server.yaml
  args:
    chdir: ~/kubespark

- name: spark role
  shell: >
    kubectl create serviceaccount spark;
    kubectl create clusterrolebinding spark-role --clusterrole=edit --serviceaccount=default:spark --namespace=default;

- name: Spark terasort repo
  git:
    repo: https://github.com/ehiggs/spark-terasort
    dest: ~/spark-terasort

- name: compile terasort
  shell: ../kubespark/build/./mvn install
  args:
    chdir: ~/spark-terasort

- name: Spark default config
  template:
    src: templates/spark-defaults.conf.j2
    dest: ~/kubespark/conf/spark-defaults.conf

- name: Spark jobs launch script
  template:
    src: templates/spark-jobs.j2
    dest: /usr/local/bin/spark-jobs
    mode: 0755
    owner: root
  become: yes
