---
- hosts: all
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: base
    - role: docker
      become: true
    - role: kubernetes
      become: true
  pre_tasks:
    - name: Ensure gitmodules update
      local_action: command git submodule update --init --recursive

- hosts: master
  serial: 1
  become: true
  strategy: linear
  roles:
    - k8s

- hosts: nodes
  serial: 1
  become: true
  strategy: linear
  roles:
    - k8s
