---
- hosts: all
  serial: 1
  become: true
  strategy: linear
  roles:
    - role: base
      become: false
    - docker
    - kubernetes

- hosts: master
  serial: 1
  become: true
  strategy: linear
  roles:
    - k8s

- hosts: nodes
  serial: 1
  become: true
  strategy: linear
  roles:
    - k8s
